### ISSUE TITLE
Why are the running results of my python script and the online demo different?

### ISSUE THREAD

**Issue by MrQinYQ** [spotify/basic-pitch#126]
i upload a canon mp3，python script return a bad result.
![KIM20240521-509471](https://github.com/spotify/basic-pitch/assets/16348159/72ba85fb-ef2a-40be-8c58-ba12a0c3421f)
![KIM20240521-607905](https://github.com/spotify/basic-pitch/assets/16348159/400486ae-4736-49c3-b31b-b8148ce911bd)
`
from basic_pitch.inference import predict_and_save
from basic_pitch import ICASSP_2022_MODEL_PATH

predict_and_save(
    ['./canon.mp3', './test1.mp3'],
    'output',
    True,
    True,
    True,
    True,
    model_or_model_path=ICASSP_2022_MODEL_PATH,
    # onset_threshold=0.5,
    # frame_threshold=0.5,
    # minimum_frequency=100,
    # maximum_frequency=3000,
)
`

**Comment by drubinstein** [comment]
A couple of questions:
- What OS are you on? If you're doing inference on non-TF, results may change slightly
- Can you check that the parameters used for the model in the website match what's used in basic-pitch?
Thanks

**Comment by MrQinYQ** [comment]
@drubinstein MacOS M2 arm64. That's non-TF. It seems to be using coremltools. parameters is match for in the website

**Comment by drubinstein** [comment]
Can you try to install tensorflow macos (basic-pitch[tf]) and see how much different it is? Are the overall results bad with CoreML?

**Comment by MrQinYQ** [comment]
I need remove coremltools? overall results bad with CoreML

**Comment by MrQinYQ** [comment]
> Can you try to install tensorflow macos (basic-pitch[tf]) and see how much different it is? Are the overall results bad with CoreML?

pip install basic-pitch[tf]. Midi files look much more normal now. Thanks.

**Comment by pulsar666** [comment]
**Title**: Notes in MIDI output are incorrect compared to the demo website

**Description**:
I'm experiencing an issue where the MIDI output generated by the `basic_pitch` library on my local machine has a lot of off notes. However, when I use the demo website, the notes seem to be correct. I'm using Windows 10.

Not all settings on the demo website seem to be present in the **predict_and_save()**, but I have tried to keep the settings as far as possible.

**Environment**:
- OS: Windows 10
- Python version: 3.11
- Basic Pitch version: latest
- TensorFlow version: latest

**Steps to Reproduce**:
1. Install the required packages:
    ```sh
    pip install basic_pitch[tf]
    ```
2. Use the following script to convert an audio file to MIDI:

    ```python
    import os
    from basic_pitch.inference import predict_and_save
    from basic_pitch import ICASSP_2022_MODEL_PATH

    def convert_to_midi(audio_file, output_directory):
        print(audio_file)
        # Verify the file exists
        if not os.path.exists(audio_file):
            raise FileNotFoundError(f"File not found: {audio_file}")

        try:
            predict_and_save(
                audio_path_list=[audio_file],  # <input-audio-path-list>
                output_directory=output_directory,  # <output-directory>
                save_midi=True,  # <save-midi>
                sonify_midi=False,  # <sonify-midi>
                save_model_outputs=True,  # <save-model-outputs>
                save_notes=True,  # <save-notes>
                model_or_model_path=ICASSP_2022_MODEL_PATH,
                maximum_frequency=3000.0,  # Maximum Pitch
            )
        except Exception as e:
            print(f"Error reading or converting audio file: {e}")
            raise

    output_dir = 'output'
    convert_to_midi("E:/Data/pycharm_projects/azimuth-melody-extraction-v2/output_directory/test-audio.wav", output_dir)
    print(f"MIDI file is saved at {output_dir}")
    ```

3. Compare the MIDI output generated by the script with the output generated by the demo website.

**Expected behavior**:
The MIDI output generated by the script should have the correct notes, similar to the output generated by the demo website.

**Actual behavior**:
The MIDI output generated by the script has a lot of off notes.

**Additional context**:
- I have verified that the audio file used for testing is the same in both cases.
- The model path used in the script is `ICASSP_2022_MODEL_PATH`.

---
