### ISSUE TITLE
Could it handle realtime transcription?

### ISSUE THREAD

**Issue by tomduncalf** [spotify/basic-pitch#19]
This is more of a question than an issue, but could `basic-pitch` handle realtime transcription of audio (with low latency)?

It seems that it expects input in chunks of two seconds if I understand the code correctly, which suggests that you'd always have at least that much latency, but I could be wrong.

**Comment by drubinstein** [comment]
Good question. The inference in TF has been tested to be 3x faster than real time(I have to double check that number) if you're using the Typescript library (coming soon) on a mid-range chromebook.

However, the post processing step currently expects the output from fully processing the audio through the model. It may be possible to modify the post processing step to work on chunks at a time, but we haven't tested the approach and expect worse quality output if we were to try it.

**Comment by tomduncalf** [comment]
That’s interesting to know, thanks for the details. I guess I was curious
whether this would ever be suitable for acoustic instrument recognition in
real time for e.g. music learning applications, where you ideally want the
feedback almost instantly. Sounds like it’s a “maybe”? :)

**Comment by drubinstein** [comment]
"Maybe" is a nice way of phrasing it :)

**Comment by supersational** [comment]
I'm intending to have a crack at implementing this, as I need it for my own project (and can imagine it being useful in many applications). I understand there will be a loss in quality which for my application is not a problem since I don't need accurate note onsets or timing information. 

Just wondering if there is a reason this is a "bad idea"? I don't think it will require retraining as I simply wish to extract note probabilities pre-post-processing. 

Any insight appreciated!

**Comment by eedeebee** [comment]
@supersational did you ever try this and could you share how it went, etc?

**Comment by supersational** [comment]
Didn't bother since no info on whether it's even possible without costly retraining... I switched to this simpler method https://github.com/alesgenova/pitch-detection-app
